export const ORDER_DELIVERED_REQUEST = "ORDER_DELIVERED_REQUEST"
export const ORDER_DELIVERED_SUCCESS = "ORDER_DELIVERED_SUCCESS"
export const ORDER_DELIVERED_FAIL = "ORDER_DELIVERED_FAIL"
export const ORDER_DELIVERED_RESET = "ORDER_DELIVERED_RESET"
